name: Deploy to k3s

on: 
  push: 
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
   - name: checkout code
     uses: actions/checkout@v4

   - name: setup kubectl
     uses: kubernetes-actions/setup-kubectl@v3
     with:
       kubenetes-version: 'v1.27.0'

   - name: Configure kubeconfig
     run: |
       mkdir -p ~/.kube
       echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
       chmod 600 ~/.kube/config

   - name: Apply Kubernetes manifest
     run: Kubectl apply -f nginx-app.yml 
